// VENTURE · Day 1 — Question Bank (50 questions, bilingual EN/AR)
module.exports = {
  round1: {
    id:'r1', title:'Innovation & Entrepreneurship', titleAr:'الابتكار وريادة الأعمال',
    pointsPerQuestion: 10, timePerQuestion: 30,
    questions: [
      {q:'What is the primary purpose of a Minimum Viable Product (MVP)?', qAr:'ما الغرض الأساسي من المنتج الأولي القابل للتطبيق (MVP)؟', options:['To launch a fully-featured product','To test core assumptions with the least effort','To attract as many users as possible on day one','To finalize the business model'], answer:1},
      {q:'Which of the following best describes a startup?', qAr:'أي مما يلي يصف الشركة الناشئة بشكل أفضل؟', options:['A small business with steady local customers','A traditional company that inherited its market','A temporary organization designed to search for a repeatable, scalable business model','A branch office of a larger corporation'], answer:2},
      {q:'What does "Product-Market Fit" mean?', qAr:'ماذا يعني "التوافق بين المنتج والسوق"؟', options:['The product has a beautiful design','The product satisfies a strong market demand','The product is cheaper than competitors','The product has many features'], answer:1},
      {q:'What is a "pivot" in a startup context?', qAr:'ما معنى "التحول" في سياق الشركات الناشئة؟', options:['Firing the team and starting over','A structured change in strategy based on validated learning','Doubling the marketing budget','Selling the company'], answer:1},
      {q:'In a Lean Canvas, what is the "Unique Value Proposition"?', qAr:'في نموذج اللين كانفس، ما هي "القيمة الفريدة المقدمة"؟', options:['The company slogan','A single, clear message explaining why your solution is different and worth buying','The price of the product','The list of features'], answer:1},
      {q:'What does "TAM" stand for in market sizing?', qAr:'ما معنى "TAM" في تحديد حجم السوق؟', options:['Total Advertising Money','Target Audience Metric','Total Addressable Market','Timely Access Model'], answer:2},
      {q:'Which stage typically comes FIRST in startup funding?', qAr:'أي مرحلة تأتي عادةً أولاً في تمويل الشركات الناشئة؟', options:['Series B','IPO','Pre-Seed / Seed','Series A'], answer:2},
      {q:'What is "customer discovery"?', qAr:'ما هو "اكتشاف العميل"؟', options:['Advertising to find customers','The process of talking to potential customers to validate the problem exists','Buying customer lists','Building a sales team'], answer:1},
      {q:'Which of these is a KEY entrepreneurial mindset trait?', qAr:'أي من التالي يُعدّ صفة أساسية في عقلية ريادة الأعمال؟', options:['Avoiding all risks','Waiting for perfect conditions','Comfort with uncertainty and rapid learning from failure','Following instructions strictly'], answer:2},
      {q:'What is a "Business Model Canvas"?', qAr:'ما هو "نموذج العمل التجاري كانفس"؟', options:['A painting of a company','A one-page visual template describing how a business creates, delivers, and captures value','A financial forecast document','A legal contract'], answer:1},
      {q:'What does "burn rate" refer to?', qAr:'ماذا يشير "معدل الحرق" (burn rate)؟', options:['How fast a product sells','How quickly a startup spends its available cash','The temperature of a data center','How often the team works overtime'], answer:1},
      {q:'Which UAE initiative launched a program to support one million Emirati youth in coding and AI skills?', qAr:'أي مبادرة إماراتية أطلقت برنامجاً لدعم مليون شاب إماراتي في مهارات البرمجة والذكاء الاصطناعي؟', options:['One Million Arab Coders','UAE Green Initiative','Emirates Space Program','Dubai Metro Expansion'], answer:0},
      {q:'What is "founder-market fit"?', qAr:'ما هو "التوافق بين المؤسس والسوق"؟', options:['The founder has a marketing degree','The founder has unique insight, passion, or experience relevant to the market they are entering','The founder is famous','The founder speaks multiple languages'], answer:1},
      {q:'Which of the following is NOT one of the classic startup roles?', qAr:'أي مما يلي ليس من الأدوار الكلاسيكية في الشركات الناشئة؟', options:['CEO — Chief Executive Officer','CTO — Chief Technology Officer','CMO — Chief Marketing Officer','CQO — Chief Quiet Officer'], answer:3},
      {q:'What is "traction" in the startup context?', qAr:'ما هو "الجذب" (traction) في سياق الشركات الناشئة؟', options:['The stickiness of tires on the road','Measurable evidence of customer demand and startup progress','The name of a co-founder','A funding round'], answer:1}
    ]
  },
  round2: {
    id:'r2', title:'AI & Technology', titleAr:'الذكاء الاصطناعي والتكنولوجيا',
    pointsPerQuestion: 10, timePerQuestion: 30,
    questions: [
      {q:'What does "AI" stand for?', qAr:'ماذا يعني "AI"؟', options:['Automatic Internet','Artificial Intelligence','Applied Innovation','Advanced Interface'], answer:1},
      {q:'What is a Large Language Model (LLM)?', qAr:'ما هو نموذج اللغة الكبير (LLM)؟', options:['A dictionary app','An AI system trained on massive text data to understand and generate language','A translation device','A search engine'], answer:1},
      {q:'What does "prompt engineering" mean?', qAr:'ماذا تعني "هندسة المطالبات" (prompt engineering)؟', options:['Building physical prompts','The skill of crafting clear instructions to get accurate, useful responses from AI','Programming robots','Fixing broken code'], answer:1},
      {q:'Which of the following is an example of Machine Learning?', qAr:'أي مما يلي مثال على التعلم الآلي؟', options:['A calculator adding two numbers','A spam filter that improves at detecting spam by learning from examples','A traffic light following a schedule','A microwave heating food'], answer:1},
      {q:'What is "computer vision"?', qAr:'ما هي "الرؤية الحاسوبية"؟', options:['A screen protector','The AI field enabling machines to interpret and understand visual information from images or video','A type of monitor','Video editing software'], answer:1},
      {q:'What is an "AI hallucination"?', qAr:'ما هي "هلوسة الذكاء الاصطناعي"؟', options:['When AI gets tired','When an AI generates confident but incorrect or fabricated information','A special AI feature','When AI crashes'], answer:1},
      {q:'Which UAE university is dedicated exclusively to graduate-level AI research?', qAr:'أي جامعة إماراتية مخصصة حصرياً لأبحاث الذكاء الاصطناعي على مستوى الدراسات العليا؟', options:['Zayed University','UAE University','Mohamed bin Zayed University of Artificial Intelligence (MBZUAI)','Khalifa University'], answer:2},
      {q:'What is "generative AI"?', qAr:'ما هو "الذكاء الاصطناعي التوليدي"؟', options:['AI that only classifies things','AI that generates new content such as text, images, audio, or code','AI that generates electricity','AI that turns on and off automatically'], answer:1},
      {q:'What does "training data" mean in AI?', qAr:'ماذا تعني "بيانات التدريب" في الذكاء الاصطناعي؟', options:['Data used to train employees','The dataset used to teach an AI model patterns and behavior','Exam questions for engineers','Data about gyms and fitness'], answer:1},
      {q:'Which of the following is a real ethical concern with AI?', qAr:'أي مما يلي يُعدّ مصدر قلق أخلاقي حقيقي بشأن الذكاء الاصطناعي؟', options:['AI runs too slowly','AI can inherit and amplify bias present in its training data','AI is too colorful','AI uses too much English'], answer:1},
      {q:'What is an "AI API"?', qAr:'ما هي "واجهة برمجة تطبيقات الذكاء الاصطناعي" (AI API)؟', options:['A physical robot','A programming interface that allows developers to send data to an AI model and get results back','A social media platform','A type of computer chip'], answer:1},
      {q:'Which task is best suited for AI automation?', qAr:'أي مهمة هي الأنسب لأتمتة الذكاء الاصطناعي؟', options:['Making a major ethical judgment about a person','Sorting thousands of images by visual similarity in seconds','Deciding a country\'s foreign policy','Choosing a family\'s religion'], answer:1},
      {q:'What is "RAG" in AI systems?', qAr:'ما هو "RAG" في أنظمة الذكاء الاصطناعي؟', options:['A dance style','Retrieval-Augmented Generation — combining AI generation with external knowledge sources','A programming language','Random Access Graphics'], answer:1},
      {q:'When using AI to build a startup product, what should you ALWAYS check?', qAr:'عند استخدام الذكاء الاصطناعي لبناء منتج شركة ناشئة، ما الذي يجب التحقق منه دائماً؟', options:['The color of the interface','The accuracy, safety, and cultural appropriateness of the AI output','Whether the AI speaks English','The brand of the laptop'], answer:1},
      {q:'What is "edge AI"?', qAr:'ما هو "الذكاء الاصطناعي الطرفي" (edge AI)؟', options:['AI running only in cloud data centers','AI running locally on devices such as phones, cameras, or IoT sensors','AI used only by engineers','AI on the edge of failing'], answer:1}
    ]
  },
  round3: {
    id:'r3', title:'IGCF Challenge Rapid-Fire', titleAr:'تحديات IGCF السريعة',
    pointsPerQuestion: 10, timePerQuestion: 25,
    questions: [
      {pillar:'Food Security', q:'The UAE imports approximately what percentage of its food?', qAr:'تستورد الإمارات ما يقارب أي نسبة من غذائها؟', options:['Around 20%','Around 50%','Around 80–90%','Around 10%'], answer:2},
      {pillar:'Food Security', q:'Which AI capability would best help farmers optimize water use for crops in the UAE?', qAr:'أي قدرة من قدرات الذكاء الاصطناعي هي الأفضل لمساعدة المزارعين على تحسين استخدام المياه للمحاصيل في الإمارات؟', options:['Sentiment analysis on social media','Computer vision + predictive ML on sensor data for soil moisture, crop health, and weather forecasting','Language translation','Music generation'], answer:1},
      {pillar:'Food Security', q:'Which UAE national initiative aims to reduce food loss and waste?', qAr:'أي مبادرة إماراتية وطنية تهدف إلى تقليل فقد وهدر الغذاء؟', options:["Ne'ma Initiative",'Emirates Mars Mission','UAE Pass','Dubai Metro Blue Line'], answer:0},
      {pillar:'Food Security', q:'Vertical farming addresses food security primarily by:', qAr:'تعالج الزراعة العمودية الأمن الغذائي بشكل أساسي عبر:', options:['Growing crops on tall buildings only for decoration','Producing more food per square meter with less water and no arable land needed','Making food cheaper by cutting quality','Replacing all farmers with robots'], answer:1},
      {pillar:'Education', q:'What is "personalized learning" using AI?', qAr:'ما هو "التعلم المخصص" باستخدام الذكاء الاصطناعي؟', options:['Every student gets the same lesson at the same pace','AI adapts lesson content, pace, and difficulty to each student\'s needs','Students choose their own teachers only','Removing teachers entirely'], answer:1},
      {pillar:'Education', q:'A big risk of using AI in education without safeguards is:', qAr:'من المخاطر الكبيرة لاستخدام الذكاء الاصطناعي في التعليم دون ضوابط:', options:['Students becoming too creative','Over-reliance on AI reducing critical thinking and originality','Classrooms becoming too quiet','Books becoming too colorful'], answer:1},
      {pillar:'Education', q:'Which of these is a real, useful AI application for teachers?', qAr:'أي من التالي يُعدّ تطبيقاً حقيقياً ومفيداً للذكاء الاصطناعي للمعلمين؟', options:['Replacing all teacher judgment','Auto-generating quiz drafts, summarizing readings, and flagging struggling students for teacher review','Grading student behavior via facial recognition without consent','Choosing student careers automatically'], answer:1},
      {pillar:'Education', q:'Which entity oversees education standards in Abu Dhabi?', qAr:'أي جهة تُشرف على معايير التعليم في أبوظبي؟', options:['ADEK — Department of Education and Knowledge','RTA — Roads and Transport Authority','DEWA — Dubai Electricity and Water Authority','ADNOC'], answer:0},
      {pillar:'Public Health', q:'Which UAE ministry manages federal public health?', qAr:'أي وزارة إماراتية تدير الصحة العامة الاتحادية؟', options:['MOHAP — Ministry of Health and Prevention','Ministry of Economy','Ministry of Culture','Ministry of Sports'], answer:0},
      {pillar:'Public Health', q:'"Proactive healthcare" powered by AI focuses on:', qAr:'الرعاية الصحية "الاستباقية" المدعومة بالذكاء الاصطناعي تركز على:', options:['Treating patients only after they become seriously ill','Predicting health risks early and preventing illness before it occurs','Building larger hospitals','Reducing medical staff'], answer:1},
      {pillar:'Public Health', q:'What is a MAJOR consideration when using AI on medical data?', qAr:'ما الاعتبار الرئيسي عند استخدام الذكاء الاصطناعي مع البيانات الطبية؟', options:['Making the interface colorful','Patient data privacy, security, and compliance with UAE PDPL','Choosing a good font','Speed of the animation'], answer:1},
      {pillar:'Public Health', q:'Which AI application is realistic for a student team to prototype in 16 days?', qAr:'أي تطبيق للذكاء الاصطناعي واقعي لفريق طلابي أن يبنيه كنموذج أولي في 16 يوماً؟', options:['A full hospital operating system replacing doctors','A symptom-checker chatbot that guides users to relevant clinics with clear medical-disclaimer messaging','An FDA-approved diagnostic imaging device','A robot surgeon'], answer:1},
      {pillar:'Environmental Transformation', q:'The UAE hosted which major global climate summit in November 2023?', qAr:'استضافت الإمارات أي قمة عالمية كبرى للمناخ في نوفمبر 2023؟', options:['COP28','G7','World Cup','Olympics'], answer:0},
      {pillar:'Environmental Transformation', q:'Which of the following is a real UAE environmental strategy?', qAr:'أي مما يلي يُعدّ استراتيجية بيئية إماراتية حقيقية؟', options:['UAE Net Zero 2050 Strategic Initiative','UAE Mars Colonization 2030','UAE Ocean Cleanup 2040','UAE Volcano Redirection 2035'], answer:0},
      {pillar:'Environmental Transformation', q:'How can AI help protect biodiversity in the UAE\'s marine ecosystems?', qAr:'كيف يمكن للذكاء الاصطناعي أن يساعد في حماية التنوع البيولوجي في النظم البحرية الإماراتية؟', options:['By hunting fish faster','By using computer vision on underwater imagery to monitor coral health, track species, and detect illegal activity','By making the sea louder','By replacing marine biologists entirely'], answer:1},
      {pillar:'Environmental Transformation', q:'Which is a REALISTIC AI application to reduce air pollution in a smart city?', qAr:'أي تطبيق واقعي للذكاء الاصطناعي يمكنه تقليل تلوث الهواء في مدينة ذكية؟', options:['AI-powered traffic optimization to reduce congestion and emissions','AI that turns the sky blue manually','AI that fines every driver randomly','AI that shuts down all cars'], answer:0},
      {pillar:'Green Economy', q:'What is the "circular economy"?', qAr:'ما هو "الاقتصاد الدائري"؟', options:['An economy shaped like a circle on a map','An economic model that reuses, repairs, and recycles resources to minimize waste','An economy that only uses coins','An economy focused on circular products only'], answer:1},
      {pillar:'Green Economy', q:'Masdar City in Abu Dhabi is known globally for:', qAr:'تشتهر مدينة مصدر في أبوظبي عالمياً بـ:', options:['Being a sustainability and clean-tech hub','Hosting the largest stadium in the world','Being the highest building in the world','Being the largest shopping mall'], answer:0},
      {pillar:'Green Economy', q:'Which of the following is a "green job"?', qAr:'أي مما يلي يُعدّ "وظيفة خضراء"؟', options:['A gardener at any company','A renewable energy engineer designing solar farms','Any office worker wearing green clothes','A retail cashier'], answer:1},
      {pillar:'Green Economy', q:'How can AI accelerate the green economy?', qAr:'كيف يمكن للذكاء الاصطناعي أن يُسرّع الاقتصاد الأخضر؟', options:['By optimizing energy grids, predicting solar/wind output, and improving recycling sorting through computer vision','By using more electricity for entertainment','By replacing all sustainability workers','By making everything a brighter color'], answer:0}
    ]
  }
};
