// VENTURE Day 1 — question bank v3 (mixed rounds, role-tagged, no pillar flow).
// EVERY round mixes all topics — innovation & entrepreneurship, AI & technology,
// design & research, business & marketing, and IGCF case challenges — so each
// elimination cut tests the full range and role suggestions stay fair per round.
// Correct answers live here and in the database only — never shipped to the browser.
// role: 'tech' | 'design' | 'business' → drives the private position suggestions.

export const ROUNDS = [
  {
    "round_number": 1,
    "title": "Round 1 · Founders Qualifier",
    "title_ar": "الجولة الأولى · تصفيات المؤسسين",
    "time_per_question": 30,
    "points_per_question": 10
  },
  {
    "round_number": 2,
    "title": "Round 2 · The Contenders",
    "title_ar": "الجولة الثانية · المنافسون",
    "time_per_question": 30,
    "points_per_question": 10
  },
  {
    "round_number": 3,
    "title": "Round 3 · Road to CEO",
    "title_ar": "الجولة الثالثة · الطريق إلى منصب الرئيس التنفيذي",
    "time_per_question": 30,
    "points_per_question": 10
  }
];

export const QUESTIONS = [
  {"r":1,"id":"r1q1","role":"design","q":"What is the primary purpose of a Minimum Viable Product (MVP)?","qAr":"ما الغرض الأساسي من المنتج الأولي القابل للتطبيق (MVP)؟","options":["To launch a fully-featured product","To test core assumptions with the least effort","To attract as many users as possible on day one","To finalize the business model"],"answer":1},
  {"r":1,"id":"r1q2","role":"business","q":"Which of the following best describes a startup?","qAr":"أي مما يلي يصف الشركة الناشئة بشكل أفضل؟","options":["A small business with steady local customers","A traditional company that inherited its market","A temporary organization searching for a repeatable, scalable business model","A branch office of a larger corporation"],"answer":2},
  {"r":1,"id":"r1q4","role":"tech","q":"What is a prototype?","qAr":"ما هو النموذج الأولي (prototype)؟","options":["The final version sold to customers","An early working model built to test how an idea functions","A marketing poster","A legal document protecting an idea"],"answer":1},
  {"r":1,"id":"r1q9","role":"design","q":"What is User Experience (UX)?","qAr":"ما هي تجربة المستخدم (UX)؟","options":["The colors used in a logo","How easy, useful, and pleasant a product feels for the person using it","The speed of the internet connection","The price customers pay"],"answer":1},
  {"r":1,"id":"r1q7","role":"business","q":"Which stage typically comes FIRST in startup funding?","qAr":"أي مرحلة تأتي عادةً أولاً في تمويل الشركات الناشئة؟","options":["Series B","IPO","Pre-Seed / Seed","Series A"],"answer":2},
  {"r":1,"id":"r2q1","role":"tech","q":"What is a Large Language Model (LLM)?","qAr":"ما هو نموذج اللغة الكبير (LLM)؟","options":["A dictionary app","An AI system trained on massive text data to understand and generate language","A translation device","A search engine"],"answer":1},
  {"r":1,"id":"r2q3","role":"tech","q":"Which of the following is an example of Machine Learning?","qAr":"أي مما يلي مثال على التعلم الآلي؟","options":["A calculator adding two numbers","A spam filter that improves by learning from examples","A traffic light following a fixed schedule","A microwave heating food"],"answer":1},
  {"r":1,"id":"r2q2","role":"design","q":"What does \"prompt engineering\" mean?","qAr":"ماذا تعني \"هندسة المطالبات\" (prompt engineering)؟","options":["Building physical prompts","Crafting clear instructions to get accurate, useful responses from AI","Programming robots","Fixing broken code"],"answer":1},
  {"r":1,"id":"r2q6","role":"business","q":"What is a \"freemium\" business model?","qAr":"ما هو نموذج العمل \"فريميوم\" (freemium)؟","options":["Everything is free forever","A free basic version attracts users, and advanced features are paid","Only premium users may register","The product is free on Fridays"],"answer":1},
  {"r":1,"id":"r2q10","role":"business","q":"Which metric BEST shows that an app keeps its users engaged over time?","qAr":"أي مقياس يُظهر بشكل أفضل أن التطبيق يحافظ على تفاعل مستخدميه مع مرور الوقت؟","options":["Total downloads on launch day","User retention — how many keep returning week after week","The number of colors in the logo","The size of the office"],"answer":1},
  {"r":1,"id":"r3q1","role":"tech","pillar":"Food Security","q":"Case: The UAE imports 80–90% of its food, and desert farms lose water to evaporation. Your startup has soil sensors and weather data. What is the strongest AI approach?","qAr":"حالة: تستورد الإمارات 80–90٪ من غذائها، وتفقد المزارع الصحراوية المياه بالتبخر. لدى شركتكم حساسات تربة وبيانات طقس. ما أقوى نهج للذكاء الاصطناعي؟","options":["Sentiment analysis of food posts on social media","Predictive ML on sensor + weather data to irrigate exactly when and where crops need it","A chatbot that tells farmers to water more","Music generation to calm the plants"],"answer":1},
  {"r":1,"id":"r3q9","role":"tech","pillar":"Public Health","q":"Case: A clinic wants to predict which patients may miss appointments so it can send reminders. What data approach is right?","qAr":"حالة: تريد عيادة توقّع المرضى الذين قد يتغيبون عن مواعيدهم لإرسال تذكيرات. ما النهج الصحيح للبيانات؟","options":["Train ML on past appointment records — with patient consent and identities protected","Post patient names publicly","Guess based on patient nationality","Call every patient every hour"],"answer":0},
  {"r":1,"id":"r3q3","role":"design","pillar":"Food Security","q":"Case: Families say your food-waste app is \"complicated\". Before rebuilding it, what should the team do FIRST?","qAr":"حالة: تقول العائلات إن تطبيقكم لتقليل هدر الطعام \"معقّد\". قبل إعادة بنائه، ما الذي يجب على الفريق فعله أولاً؟","options":["Add a tutorial video and more menus","Observe five families using it to find exactly where they get stuck","Change the logo","Lower the price"],"answer":1},
  {"r":1,"id":"r3q5","role":"design","pillar":"Education","q":"Case: An AI tutor gives Grade 6 students instant full answers, and teachers report weaker problem-solving. How should the design change?","qAr":"حالة: معلّم ذكاء اصطناعي يعطي طلاب الصف السادس الإجابات كاملة فوراً، ويلاحظ المعلمون ضعفاً في حل المشكلات. كيف يجب تعديل التصميم؟","options":["Give answers faster","Guide with hints and step-by-step questions, revealing full answers only after real attempts","Remove the AI entirely","Make the answers longer"],"answer":1},
  {"r":1,"id":"r3q2","role":"business","pillar":"Food Security","q":"Case: A Sharjah restaurant group throws away safe, unsold food nightly, while charities need donations. What business model connects them best?","qAr":"حالة: مجموعة مطاعم في الشارقة تتخلص يومياً من طعام سليم غير مُباع، بينما تحتاج الجمعيات الخيرية إلى تبرعات. أي نموذج عمل يربط بينهما بشكل أفضل؟","options":["A platform matching surplus food to charities in real time, funded by restaurant sustainability fees","A cooking show","Selling the food abroad","An app that photographs waste without acting"],"answer":0},
  {"r":2,"id":"r1q5","role":"business","q":"In a Lean Canvas, what is the \"Unique Value Proposition\"?","qAr":"في نموذج اللين كانفس، ما هي \"القيمة الفريدة المقدمة\"؟","options":["The company slogan","A single, clear message explaining why your solution is different and worth choosing","The price of the product","The list of features"],"answer":1},
  {"r":2,"id":"r1q8","role":"design","q":"What is \"customer discovery\"?","qAr":"ما هو \"اكتشاف العميل\"؟","options":["Advertising to find customers","Talking to potential customers to validate that the problem really exists","Buying customer lists","Building a sales team"],"answer":1},
  {"r":2,"id":"r1q10","role":"tech","q":"In a one-day build challenge, what should a team build FIRST?","qAr":"في تحدي بناء يستمر يوماً واحداً، ما الذي يجب أن يبنيه الفريق أولاً؟","options":["The settings page","One working version of the single most important feature","The company logo in ten colors","A 50-page business plan"],"answer":1},
  {"r":2,"id":"r1q11","role":"business","q":"What does \"burn rate\" refer to?","qAr":"إلامَ يشير \"معدل الحرق\" (burn rate)؟","options":["How fast a product sells","How quickly a startup spends its available cash","The temperature of a data center","How often the team works overtime"],"answer":1},
  {"r":2,"id":"r1q12","role":"design","q":"What is the BEST way to learn whether users understand your app?","qAr":"ما أفضل طريقة لمعرفة ما إذا كان المستخدمون يفهمون تطبيقك؟","options":["Ask your best friend if it looks nice","Watch real users try to complete a task without helping them","Count how many features it has","Check if the code compiles"],"answer":1},
  {"r":2,"id":"r2q4","role":"tech","q":"What is \"computer vision\"?","qAr":"ما هي \"الرؤية الحاسوبية\"؟","options":["A screen protector","The AI field enabling machines to interpret images and video","A type of monitor","Video editing software"],"answer":1},
  {"r":2,"id":"r2q5","role":"design","q":"What is an \"AI hallucination\", and why must teams check for it?","qAr":"ما هي \"هلوسة الذكاء الاصطناعي\"، ولماذا يجب على الفرق التحقق منها؟","options":["When AI gets tired — no need to check","When AI generates confident but false information — outputs must be verified before use","A special AI feature for creativity","When AI crashes"],"answer":1},
  {"r":2,"id":"r2q7","role":"tech","q":"What is an \"AI API\"?","qAr":"ما هي \"واجهة برمجة تطبيقات الذكاء الاصطناعي\" (AI API)؟","options":["A physical robot","A programming interface that lets developers send data to an AI model and get results back","A social media platform","A type of computer chip"],"answer":1},
  {"r":2,"id":"r2q11","role":"business","q":"Investors often ask an AI startup about its \"moat\". What does that mean?","qAr":"غالباً ما يسأل المستثمرون الشركة الناشئة في الذكاء الاصطناعي عن \"الخندق التنافسي\" (moat). ماذا يعني ذلك؟","options":["The building's security system","A durable advantage — such as unique data or technology — that competitors can't easily copy","The company swimming pool","A type of loan"],"answer":1},
  {"r":2,"id":"r2q12","role":"business","q":"When pitching an AI product, what should the FIRST slide focus on?","qAr":"عند عرض منتج ذكاء اصطناعي، على ماذا يجب أن تركز الشريحة الأولى؟","options":["The team's favorite programming language","The real problem and who suffers from it","The office location","The font choices"],"answer":1},
  {"r":2,"id":"r3q12","role":"tech","pillar":"Public Health","q":"Case: Health data in your app must comply with UAE data protection law. Which practice is essential?","qAr":"حالة: يجب أن تتوافق البيانات الصحية في تطبيقكم مع قانون حماية البيانات الإماراتي. أي ممارسة أساسية؟","options":["Store everything openly for transparency","Encrypt patient data, limit access, and collect only what is needed with consent","Sell the data to fund the startup","Keep data on a personal USB drive"],"answer":1},
  {"r":2,"id":"r3q13","role":"tech","pillar":"Environmental Transformation","q":"Case: Sharjah's coast needs continuous coral-reef health monitoring, but diver surveys are slow and rare. What is the strongest AI solution?","qAr":"حالة: تحتاج سواحل الشارقة إلى مراقبة مستمرة لصحة الشعاب المرجانية، لكن مسح الغواصين بطيء ونادر. ما أقوى حل بالذكاء الاصطناعي؟","options":["Ask fishermen to report monthly","Computer vision on underwater camera feeds to track coral health and detect changes automatically","Play sounds to the coral","Ban swimming"],"answer":1},
  {"r":2,"id":"r3q10","role":"design","pillar":"Public Health","q":"Case: Elderly users abandon your health-check app at the registration screen. What is the FIRST fix to try?","qAr":"حالة: كبار السن يتوقفون عن استخدام تطبيقكم الصحي عند شاشة التسجيل. ما أول حل يجب تجربته؟","options":["Add more registration fields for accuracy","Simplify sign-up to the minimum steps, with large text and clear language","Advertise more","Target younger users instead"],"answer":1},
  {"r":2,"id":"r3q15","role":"design","pillar":"Environmental Transformation","q":"Case: Your recycling app shows charts of global data, but users say it \"doesn't feel relevant\". What redesign helps most?","qAr":"حالة: تطبيق إعادة التدوير لديكم يعرض رسوماً لبيانات عالمية، لكن المستخدمين يقولون إنه \"غير مرتبط بهم\". أي إعادة تصميم تساعد أكثر؟","options":["Add more global charts","Show each user their OWN neighborhood impact and simple next actions","Use brighter colors only","Remove all numbers"],"answer":1},
  {"r":2,"id":"r3q4","role":"business","pillar":"Food Security","q":"Case: Your vertical-farm startup produces greens using 90% less water, but costs more than imports. Which first customer makes the strongest launch?","qAr":"حالة: مزرعتكم العمودية تنتج خضروات بمياه أقل بنسبة 90٪ لكن بتكلفة أعلى من المستورد. أي عميل أول يمنحكم أقوى انطلاقة؟","options":["Price-sensitive wholesale markets","Hotels and restaurants that market \"locally grown, sustainable\" to their guests","Random online buyers worldwide","No customers — keep researching for a year"],"answer":1},
  {"r":3,"id":"r1q3","role":"business","q":"What does \"Product-Market Fit\" mean?","qAr":"ماذا يعني \"التوافق بين المنتج والسوق\"؟","options":["The product has a beautiful design","The product satisfies a strong market demand","The product is cheaper than competitors","The product has many features"],"answer":1},
  {"r":3,"id":"r1q6","role":"tech","q":"For a founder with limited coding experience, what is the FASTEST way to build a working app prototype today?","qAr":"بالنسبة لمؤسس ذي خبرة برمجية محدودة، ما أسرع طريقة اليوم لبناء نموذج أولي عامل لتطبيق؟","options":["Hire a large engineering team first","Use no-code tools and AI coding assistants to assemble the core feature","Wait until learning advanced programming","Buy an existing company"],"answer":1},
  {"r":3,"id":"r1q13","role":"design","q":"What is \"founder-market fit\"?","qAr":"ما هو \"التوافق بين المؤسس والسوق\"؟","options":["The founder has a marketing degree","The founder has unique insight, passion, or lived experience relevant to the market","The founder is famous","The founder speaks multiple languages"],"answer":1},
  {"r":3,"id":"r1q14","role":"tech","q":"What does \"scalable\" mean for a tech product?","qAr":"ماذا تعني \"قابلية التوسع\" لمنتج تقني؟","options":["It can serve many more users without breaking or costing much more per user","It has a large physical size","It can be weighed on a scale","It only works for one school"],"answer":0},
  {"r":3,"id":"r1q15","role":"tech","q":"What is the main responsibility of a startup's Technical Lead?","qAr":"ما المسؤولية الأساسية للقائد التقني في الشركة الناشئة؟","options":["Designing the marketing campaign","Choosing the tools and building the working product","Signing legal contracts","Managing the office furniture"],"answer":1},
  {"r":3,"id":"r2q8","role":"design","q":"What does \"training data\" mean in AI?","qAr":"ماذا تعني \"بيانات التدريب\" في الذكاء الاصطناعي؟","options":["Data used to train employees","The dataset used to teach an AI model its patterns and behavior","Exam questions for engineers","Data about gyms and fitness"],"answer":1},
  {"r":3,"id":"r2q9","role":"design","q":"Your team's AI feature works for you but confuses first-time users. What should you do BEFORE launch?","qAr":"ميزة الذكاء الاصطناعي في مشروعكم تعمل معكم لكنها تربك المستخدمين الجدد. ما الذي يجب فعله قبل الإطلاق؟","options":["Launch anyway — users will adapt","Run a small pilot test with real users and redesign based on what confuses them","Add more buttons","Remove the feature secretly"],"answer":1},
  {"r":3,"id":"r2q13","role":"tech","q":"What is \"RAG\" in AI systems?","qAr":"ما هو \"RAG\" في أنظمة الذكاء الاصطناعي؟","options":["A dance style","Retrieval-Augmented Generation — combining AI generation with external knowledge sources","A programming language","Random Access Graphics"],"answer":1},
  {"r":3,"id":"r2q14","role":"design","q":"Which is a real ethical concern when designing AI products?","qAr":"أي مما يلي يُعدّ مصدر قلق أخلاقي حقيقي عند تصميم منتجات الذكاء الاصطناعي؟","options":["AI runs too slowly","AI can inherit and amplify bias present in its training data","AI is too colorful","AI uses too much English"],"answer":1},
  {"r":3,"id":"r2q15","role":"business","q":"Your AI study app is ready. Which launch plan builds trust with schools FASTEST?","qAr":"تطبيقكم الدراسي بالذكاء الاصطناعي جاهز. أي خطة إطلاق تبني الثقة مع المدارس بشكل أسرع؟","options":["Send one mass email to every school in the country","Partner with two schools for a free pilot, gather results, then share the success stories","Wait for schools to discover it alone","Advertise only on gaming channels"],"answer":1},
  {"r":3,"id":"r3q6","role":"tech","pillar":"Education","q":"Case: A school wants an AI assistant that answers questions ONLY from its own approved textbooks, never from the open internet. Which technique fits best?","qAr":"حالة: تريد مدرسة مساعد ذكاء اصطناعي يجيب فقط من كتبها المعتمدة، وليس من الإنترنت المفتوح. أي تقنية تناسب ذلك؟","options":["A bigger model with no restrictions","Retrieval-Augmented Generation (RAG) over the school's own documents","Turning off the internet in the school","Printing more textbooks"],"answer":1},
  {"r":3,"id":"r3q7","role":"business","pillar":"Education","q":"Case: Your study app helps students, but schools hesitate to pay. Parents ask to buy it directly. What is the smartest next move?","qAr":"حالة: تطبيقكم الدراسي يفيد الطلاب، لكن المدارس تتردد في الدفع، بينما يطلب أولياء الأمور شراءه مباشرة. ما أذكى خطوة تالية؟","options":["Refuse parents and wait for schools","Test a parent subscription now, and use its success data to convince schools later","Make everything free forever","Stop the project"],"answer":1},
  {"r":3,"id":"r3q8","role":"design","pillar":"Education","q":"Case: You must prove your reading app works before a school pilot. Which evidence is MOST convincing?","qAr":"حالة: عليكم إثبات فعالية تطبيق القراءة قبل تجربته في مدرسة. أي دليل هو الأكثر إقناعاً؟","options":["The app has a beautiful icon","A before/after test showing reading scores improved for students who used it","The team worked very hard","It uses the newest AI model"],"answer":1},
  {"r":3,"id":"r3q11","role":"business","pillar":"Public Health","q":"Case: Your symptom-guidance chatbot is accurate, but hospitals worry about liability. What makes partnership discussions EASIER?","qAr":"حالة: روبوت الإرشاد الصحي لديكم دقيق، لكن المستشفيات قلقة من المسؤولية القانونية. ما الذي يسهّل محادثات الشراكة؟","options":["Promise the AI is never wrong","Position it as guidance that directs users to clinics — with clear medical disclaimers and human review","Hide the AI part","Avoid hospitals completely"],"answer":1},
  {"r":3,"id":"r3q14","role":"business","pillar":"Environmental Transformation","q":"Case: Your AI traffic system could cut emissions, aligning with UAE Net Zero 2050. Who is the RIGHT first customer?","qAr":"حالة: نظام المرور الذكي لديكم يمكنه خفض الانبعاثات بما يتوافق مع استراتيجية الإمارات للحياد المناخي 2050. من هو العميل الأول المناسب؟","options":["Individual drivers one by one","A city or transport authority piloting it on real intersections","A toy store","A social media influencer"],"answer":1},
  {"r":3,"id":"r3q16","role":"business","pillar":"Environmental Transformation","q":"Case: COP28 raised demand for measurable sustainability. Companies ask your startup to \"prove impact\". What should you sell them?","qAr":"حالة: رفع مؤتمر COP28 الطلب على استدامة قابلة للقياس. تطلب الشركات من شركتكم الناشئة \"إثبات الأثر\". ما الذي يجب أن تبيعوه لهم؟","options":["A green logo package","Reports with verified, measurable numbers — emissions cut, water saved — they can publish","A promise without data","Stickers for their office"],"answer":1},
  {"r":3,"id":"r3q17","role":"tech","pillar":"Green Economy","q":"Case: A recycling plant sorts waste by hand, slowly and with errors. Which AI upgrade raises capacity most directly?","qAr":"حالة: مصنع إعادة تدوير يفرز النفايات يدوياً ببطء وبأخطاء. أي تطوير بالذكاء الاصطناعي يرفع الطاقة الإنتاجية بشكل مباشر؟","options":["A chatbot for the workers","Computer-vision sorting that identifies materials on the conveyor in real time","New uniforms","A louder alarm system"],"answer":1},
  {"r":3,"id":"r3q18","role":"business","pillar":"Green Economy","q":"Case: Masdar City invites startups to pilot clean-tech. Your solar-cleaning robot works but is unknown. Why is this pilot worth more than immediate sales?","qAr":"حالة: تدعو مدينة مصدر الشركات الناشئة لتجربة تقنيات نظيفة. روبوت تنظيف الألواح الشمسية لديكم يعمل لكنه غير معروف. لماذا تفوق قيمة هذه التجربة المبيعات الفورية؟","options":["Free office furniture","A credible reference customer and real performance data that unlock bigger clients and investors","It doesn't — pilots waste time","Masdar pays the highest prices"],"answer":1},
  {"r":3,"id":"r3q19","role":"design","pillar":"Green Economy","q":"Case: You are researching why families in Sharjah don't recycle, before building anything. Which question gives the MOST useful insight?","qAr":"حالة: تبحثون لماذا لا تعيد العائلات في الشارقة التدوير، قبل بناء أي حل. أي سؤال يمنحكم الرؤية الأكثر فائدة؟","options":["\"Do you agree recycling is good?\"","\"Walk me through what happens to your household waste on a normal day.\"","\"Would you use our app?\"","\"What is your favorite color for bins?\""],"answer":1},
  {"r":3,"id":"r3q20","role":"tech","pillar":"Green Economy","q":"Case: A solar farm's output drops unpredictably on some days. Which AI approach finds the cause AND predicts future dips?","qAr":"حالة: ينخفض إنتاج مزرعة شمسية بشكل غير متوقع في بعض الأيام. أي نهج للذكاء الاصطناعي يكشف السبب ويتنبأ بالانخفاضات القادمة؟","options":["Delete the bad days from the data","ML on panel sensors + weather + dust data to detect patterns and forecast output","Repaint the panels","Check the panels once a year"],"answer":1}
];
